from setuptools import setup, find_packages

setup(
    name='vla_integration',
    version='0.1.0',
    packages=find_packages(),
    install_requires=[
        'openai>=1.0.0',
        'fastapi>=0.100.0',
        'uvicorn>=0.20.0',
        'pydantic>=2.0.0',
        'python-multipart>=0.0.6',
        'numpy>=1.21.0',
        'opencv-python>=4.5.0',
        'torch>=1.9.0',
        'transformers>=4.20.0',
        'pyaudio>=0.2.11',
        'sounddevice>=0.4.6',
        'websockets>=10.0',
    ],
    author='AI Robotics Team',
    author_email='team@airobotics.example.com',
    description='Vision-Language-Action (VLA) Integration for ROS 2 Humanoid Robotics',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/airobotics/vla-integration',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Education',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
    ],
    python_requires='>=3.8',
)